from enum import Enum

class Call(Enum):
    Seven = 0,
    SevenVip = 1,
    SevenGode = 2,
    SevenHalve = 3,
    SevenSang = 4,
    Eight = 5,
    EightVip = 6,
    EightGode = 7,
    EightHalve = 8,
    EightSang = 9,
    Nine = 10,
    NineVip = 11,
    NineGode = 12,
    NineHalve = 13,
    NineSang = 14,
    Ten = 15,
    TenVip = 16,
    TenGode = 17,
    TenHalve = 18,
    TenSang = 19,
    Eleven = 20,
    ElevenVip = 21,
    ElevenGode = 22,
    ElevenHalve = 23,
    ElevenSang = 24,
    Twelve = 25,
    TwelveVip = 26,
    TwelveGode = 27,
    TwelveHalve = 28,
    TwelveSang = 29,
    Thirteen = 30,
    ThirteenVip = 31,
    ThirteenGode = 32,
    ThirteenHalve = 33,
    ThirteenSang = 34
